### ISSUE TITLE
Bootstrap returns a 403 response upon connecting to update server.

### ISSUE THREAD

**Issue by JustinHarper** [MC-Venture/Launcher#2]
The launcher bootstrap is returning a 403 response upon attempting to connect to the update server while when directly going to the news URL in a browser it displays fine. This is not the expected behavior and is similar to the [previous bug report](https://github.com/MC-Venture/Launcher/issues/1).

The error is show below...

```
To report this error, provide:

java.io.IOException: Did not get expected response code, got 403 for https://update.mc-venture.net/launcher/latest.json
	at com.skcraft.launcher.bootstrap.HttpRequest.expectResponseCode(HttpRequest.java:154)
	at com.skcraft.launcher.bootstrap.Downloader.execute(Downloader.java:74)
	at com.skcraft.launcher.bootstrap.Downloader.run(Downloader.java:42)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by JustinHarper** [comment]
Fixed in commit 0a45771c4e5b3451f95dcf88e97ee7b6491b613d.

Issue was caused by launcher not sending a user agent with the HTTP connection.

Same issue as the [previous bug report](https://github.com/MC-Venture/Launcher/issues/1)
